'''
Project Euler: Problem 2: Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence that do not exceed the nth term,
find the sum of the even-valued terms.
'''

def fiboEvenSum(n):
    fib1, fib2 = 1, 1
    total = 0
    for i in range(n):
        if fib2%2 == 0:
            total += fib2
        fib1, fib2 = fib2, fib1+fib2
    return total

print(fiboEvenSum(10))
